function Products() {
  const pro = [
    {
      id: 1,
      title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
      price: 109.95,
      description:
        "Your perfect pack for everyday use and walks in the forest...",
      category: "men",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuBZJFuK_F8E81-uW-Agy97_6sNFr9fnKWeg&s",
      rating: { rate: 3.9, count: 120 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "trending",
    },
    {
      id: 2,
      title: "Mens Casual Premium Slim Fit T-Shirts",
      price: 22.3,
      description: "Slim-fitting style, contrast raglan long sleeve...",
      category: "men",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5h92bAfWkZku-RCv3lUeXWvlSxsEm7Ih2fA&s",
      rating: { rate: 4.1, count: 259 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "best sale",
    },
    {
      id: 3,
      title: "Mens Cotton Jacket",
      price: 55.99,
      description: "Great outerwear jackets for Spring/Autumn/Winter...",
      category: "men",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_1Px94vFl24Z8hODQ0OZX7dUo1pLajIJQ-w&s",
      rating: { rate: 4.7, count: 500 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "best sale",
    },
    {
      id: 4,
      title: "Mens Casual Slim Fit",
      price: 15.99,
      description: "The color could be slightly different...",
      category: "men",
      image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
      rating: { rate: 2.1, count: 430 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "random",
    },
    {
      id: 5,
      title: "John Hardy Women's Legends Naga...",
      price: 695,
      description: "From our Legends Collection, the Naga...",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
      rating: { rate: 4.6, count: 400 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "trending",
    },
    {
      id: 6,
      title: "Solid Gold Petite Micropave",
      price: 168,
      description: "Satisfaction Guaranteed...",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
      rating: { rate: 3.9, count: 70 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "new",
    },
    {
      id: 7,
      title: "White Gold Plated Princess",
      price: 9.99,
      description: "Classic Created Wedding Engagement...",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
      rating: { rate: 3, count: 400 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "trenning",
    },
    {
      id: 8,
      title: "Pierced Owl Rose Gold Plated",
      price: 10.99,
      description: "Rose Gold Plated Double Flared...",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
      rating: { rate: 1.9, count: 100 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "new",
    },
    {
      id: 9,
      title: "WD 2TB Elements Portable External Hard Drive",
      price: 64,
      description: "USB 3.0 and USB 2.0 Compatibility...",
      category: "electronics",
      image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
      rating: { rate: 3.3, count: 203 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "trending",
    },
    {
      id: 10,
      title: "SanDisk SSD PLUS 1TB Internal SSD",
      price: 109,
      description: "Easy upgrade for faster boot up...",
      category: "electronics",
      image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
      rating: { rate: 2.9, count: 470 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "new",
    },
    {
      id: 11,
      title: "Silicon Power 256GB SSD 3D NAND",
      price: 109,
      description: "3D NAND flash are applied to deliver...",
      category: "electronics",
      image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
      rating: { rate: 4.8, count: 319 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "best sale",
    },
    {
      id: 12,
      title: "WD 4TB Gaming Drive for PS4",
      price: 114,
      description: "Expand your PS4 gaming experience...",
      category: "electronics",
      image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
      rating: { rate: 4.8, count: 400 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "best sale",
    },
    {
      id: 13,
      title: "Acer SB220Q 21.5 inch Monitor",
      price: 599,
      description: "21. 5 inches Full HD (1920 x 1080)...",
      category: "electronics",
      image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
      rating: { rate: 2.9, count: 250 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "new",
    },
    {
      id: 14,
      title: "Samsung 49-Inch CHG90 Gaming Monitor",
      price: 999.99,
      description: "49 INCH SUPER ULTRAWIDE 32:9 CURVED...",
      category: "electronics",
      image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
      rating: { rate: 2.2, count: 140 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "random",
    },
    {
      id: 15,
      title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket",
      price: 56.99,
      description: "Note: The Jacket is US standard size...",
      category: "women",
      image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
      rating: { rate: 2.6, count: 235 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "new",
    },
    {
      id: 16,
      title: "Lock and Love Women's Faux Leather Jacket",
      price: 29.95,
      description: "100% POLYURETHANE(shell)...",
      category: "women",
      image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
      rating: { rate: 2.9, count: 340 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "best sale",
    },
    {
      id: 17,
      title: "Rain Jacket Women Windbreaker",
      price: 39.99,
      description: "Lightweight perfect for trip or casual wear...",
      category: "women",
      image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
      rating: { rate: 3.8, count: 679 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "trending",
    },
    {
      id: 18,
      title: "MBJ Women's Short Sleeve Boat Neck",
      price: 9.85,
      description: "95% RAYON 5% SPANDEX...",
      category: "women",
      image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
      rating: { rate: 4.7, count: 130 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "best sale",
    },
    {
      id: 19,
      title: "Opna Women's Short Sleeve Moisture",
      price: 7.95,
      description: "100% Polyester, Machine wash...",
      category: "women",
      image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
      rating: { rate: 4.5, count: 146 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "trending",
    },
    {
      id: 20,
      title: "DANVOUY Women's T Shirt Casual Cotton",
      price: 12.99,
      description: "95% Cotton, 5% Spandex...",
      category: "women",
      image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
      rating: { rate: 3.6, count: 145 },
      secondimage: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzCozd-8vgtLVHAO8p1N1giSaaPSlmiCdsTA&s",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-01.jpg?v=1686743695",
        "https://zpacks.com/cdn/shop/files/Zpacks-TrailCoolMerinoWoolT-Shirt-02_1200x1200.jpg?v=1686743695",
      ],
      tag: "new",
    },
  ];

  return pro;
}

export default Products;
